## Custom Dockerfile
FROM consol/ubuntu-xfce-vnc
ENV REFRESHED_AT 2018-03-18

## Switch to root USER 1000 to switch back
# USER 0
#RUN apt-get update
#RUN apt-get install -y yum
#RUN yum install -y gedit \
#    && yum clean all
# RUN apt-get update
# RUN apt-get upgrade -y
# RUN apt-get install -y git
# RUN apt-get install -y gnupg
# RUN apt-get install -y python 
# RUN apt-get install -y curl
# RUN curl -sL https://deb.nodesource.com/setup_6.x > setupsource
# RUN chmod 755 setupsource
# RUN ./setupsource -E bash -
# RUN apt-get install -y nodejs
# RUN curl https://www.npmjs.com/install.sh > install.sh
# RUN chmod 755 install.sh
# RUN ./install.sh
# RUN git clone https://github.com/nuxt/todomvc.git
# WORKDIR /todomvc
# RUN npm i @feathersjs/feathers
# #RUN npm install @feathersjs/cli -g
# RUN npm install ajv
# RUN npm install ajv-keywords
# RUN npm install nuxt --save
# #RUN npm install -g loopback-cli
# RUN npm install @vue/cli @vue/cli-init
# RUN npm install
# #RUN npm audit fix
# #RUN npm run dev
# #RUN $ip='10.0.75.1'
# #RUN $cmd="export DISPLAY=${ip}:0; code -w ."
# #RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
# #RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
# #RUN apt-get update
# #RUN apt-cache policy docker-ce
# #RUN apt-get install -y docker-ce
# #RUN docker run --rm ctaggart/golang-vscode su - vscode -c $cmd
# RUN apt install -y gdebi-core
# COPY code_1.26.0-1534177765_amd64.deb code_1.26.0-1534177765_amd64.deb
# RUN apt install -y libgconf-2-4
# RUN apt --fix-broken install
# RUN gdebi code_1.26.0-1534177765_amd64.deb | apt-get install -f
# RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
# RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
# RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
# RUN apt-get update
# RUN apt-get install -y code
# RUN USER 1000
